apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: helbreder
  name: ingress-helbreder
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - helbreder.online
      secretName: helbreder-online
  rules:
  - host: helbreder.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: helbreder
            port:
              number: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: helbreder
  namespace: helbreder
spec:
  type: ClusterIP
  selector:
    app: helbreder
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000