apiVersion: apps/v1
kind: Deployment
metadata:
  name: helbreder
  namespace: helbreder
spec:
  selector:
    matchLabels:
      app: helbreder
  replicas: 1
  template:
    metadata:
      labels:
        app: helbreder
    spec:
      containers:
      - name: nginx
        image: wiktorkisielewski/helbreder:alpha_0.7.42
        ports:
          - containerPort: 5000
        env:
          - name: POSTGRES_IP
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_IP
                name: env
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_PASSWORD
                name: env
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_USER
                name: env
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_DB
                name: env
          - name: POSTGRES_PORT
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_PORT
                name: env
          - name: AUTH_USER
            valueFrom:
              configMapKeyRef:
                key: AUTH_USER
                name: env
          - name: AUTH_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: AUTH_PASSWORD
                name: env
#           - name: RSA_KEY
#             valueFrom:
#               configMapKeyRef:
#                 key: RSA_KEY
#                 name: env
#           - name: RSA_PASSWORD
#             valueFrom:
#               configMapKeyRef:
#                 key: RSA_PASSWORD
#                 name: env
          - name: SECRET_KEY
            valueFrom:
              configMapKeyRef:
                key: SECRET_KEY
                name: env
          - name: EMAIL
            valueFrom:
              configMapKeyRef:
                key: EMAIL
                name: env
          - name: EMAIL_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: EMAIL_PASSWORD
                name: env
          - name: MODULE_POSTGRES_IP
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_IP
                name: psql-module-env
          - name: MODULE_POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_PASSWORD
                name: psql-module-env
          - name: MODULE_POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_USER
                name: psql-module-env
          - name: MODULE_POSTGRES_PORT
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_PORT
                name: psql-module-env
