name: Helbreder [docker]

on:
  push:
    branches:
      - '*'

jobs:
  helbreder:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'helbreder:')"
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: checkout 
        uses: actions/checkout@v2
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: ./core
          tags: |
            wiktorkisielewski/${{ github.event.head_commit.message }}
          push: true